In [44]:
import pandas as pd

In [45]:
## Loading the datasets

climate_df = pd.read_csv('Climate1985_2020/3WeeksRunningAvg/Canola_TWN_PRA_1985_2020_Climate_MovingAvg_week40.txt',sep='\t')
nvdi_df = pd.read_csv('NDVI_MODIS/3weekMovingAvg/Canola_TWP_MovingAvg.csv')
ecv_smos_df = pd.read_csv('ECV_SMOS2010-2020/TWN_Canola_ECV_SMOS_Weekly_20100101.20201231.csv')
crop_yield_canola_df = pd.read_excel('Crop_Yield/Yield2010_2021_SKMB_Canola_Township_ED.xlsx')

In [46]:
climate_df.head(5)

,TWN_ID,Year,SumPcpn18_20,SumPcpn19_21,SumPcpn20_22,SumPcpn21_23,SumPcpn22_24,SumPcpn23_25,SumPcpn24_26,SumPcpn25_27,...,AvgPrcnAWHC29_31,AvgPrcnAWHC30_32,AvgPrcnAWHC31_33,AvgPrcnAWHC32_34,AvgPrcnAWHC33_35,AvgPrcnAWHC34_36,AvgPrcnAWHC35_37,AvgPrcnAWHC36_38,AvgPrcnAWHC37_39,AvgPrcnAWHC38_40
0,00101E1,1985,32.0,34.5,29.5,35.5,43.7,24.7,80.7,74.5,...,0.124762,0.259048,0.507143,0.753810,0.860952,0.883333,0.849524,0.848095,0.853810,0.869048
1,00101E1,1986,30.2,19.6,5.4,26.9,40.7,73.2,51.9,50.3,...,0.437619,0.288095,0.177619,0.074286,0.037619,0.055714,0.090952,0.147143,0.198571,0.290476
2,00101E1,1987,14.4,37.9,59.9,61.2,40.7,50.7,51.6,54.6,...,0.483333,0.365714,0.310000,0.415238,0.534286,0.570476,0.547143,0.551429,0.580000,0.586667
3,00101E1,1988,34.9,22.9,19.0,0.0,14.3,16.7,16.7,27.7,...,0.004286,0.027619,0.109524,0.164286,0.179524,0.142381,0.166190,0.216190,0.251905,0.247619
4,00101E1,1989,27.4,37.5,40.5,51.1,52.0,67.4,84.4,67.0,...,0.110952,0.194286,0.318095,0.384762,0.439524,0.459048,0.489048,0.509048,0.518571,0.480000

In [47]:
nvdi_df.head(5)

,TWP_ID,YEAR,NDVI18_20,NDVI19_21,NDVI20_22,NDVI21_23,NDVI22_24,NDVI23_25,NDVI24_26,NDVI25_27,...,NDVI28_30,NDVI29_31,NDVI30_32,NDVI31_33,NDVI32_34,NDVI33_35,NDVI34_36,NDVI35_37,NDVI36_38,NDVI_MAX
0,00101E1,2000,0.258661,0.311686,0.401711,0.471207,0.556656,0.593430,0.658336,0.696674,...,0.759668,0.714705,0.666111,0.608262,0.550412,0.515353,0.493043,0.476926,0.434332,0.800998
1,00101E1,2001,0.271472,0.299149,0.329158,0.360734,0.411387,0.476161,0.555059,0.633956,...,0.769349,0.775585,0.738828,0.683502,0.625861,0.568261,0.506879,0.442404,0.377830,0.795588
2,00101E1,2002,0.226186,0.242399,0.254109,0.294525,0.324490,0.381464,0.437595,0.535246,...,0.730935,0.725283,0.697976,0.655635,0.615383,0.570338,0.539687,0.518576,0.477932,0.739600
3,00101E1,2003,0.244343,0.277896,0.319315,0.392025,0.473263,0.552172,0.615737,0.665826,...,0.747671,0.736302,0.702264,0.630573,0.528436,0.454829,0.425106,0.410432,0.384892,0.769433
4,00101E1,2004,0.235770,0.250572,0.258847,0.290806,0.342773,0.419997,0.489744,0.552942,...,0.643874,0.622110,0.667781,0.690917,0.708486,0.663586,0.624549,0.581973,0.547010,0.759248

In [48]:
ecv_smos_df.head(5)

,TWP_ID,VALID_COUNT,MIN,MAX,RANGE,MEAN,TOTAL_COUNT,YEAR,DOY,WEEK
0,00101E1,98,32.693829,32.693829,0.000000,32.693825,98,2011,129,19
1,00101W1,95,30.032328,32.693829,2.661501,30.844786,95,2011,129,19
2,00101W2,90,31.222174,31.222174,0.000000,31.222170,90,2011,129,19
3,00102E1,87,32.693829,39.018414,6.324585,35.456284,87,2011,129,19
4,00102W1,95,30.032328,30.032328,0.000000,30.032320,95,2011,129,19

In [49]:
crop_yield_canola_df.head(5)

,OBJECTID,TWP_ID,YieldKgAcre2010,YieldKgAcre2011,YieldKgAcre2012,YieldKgAcre2013,YieldKgAcre2014,YieldKgAcre2015,YieldKgAcre2016,YieldKgAcre2017,YieldKgAcre2018,YieldKgAcre2019,YieldKgAcre2020,YieldKgAcre2021,ECODISTRICT_ID,ECOREGION_ID,ECOZONE_ID,ECOPROVINCE_ID
0,1,00101E1,867.766846,746.765442,787.231293,1131.823547,881.470978,927.640442,739.822205,1260.589233,1169.278442,1150.015503,1131.083313,994.528046,852,162,10,10.1
1,2,00101W1,673.685028,670.953613,799.348114,1051.479919,990.792786,948.919067,704.518585,1208.910278,1149.666138,1140.450867,1126.362488,992.523376,852,162,10,10.1
2,3,00101W2,824.303864,591.453003,677.236389,839.030914,778.580139,686.634338,950.681091,872.101929,814.256714,916.208557,989.483490,782.133820,796,157,10,10.3
3,4,00101W3,432.694122,257.083649,412.948364,738.874359,466.009613,613.363098,1069.693237,268.218826,510.997971,765.065826,617.296875,291.780167,832,159,10,10.3
4,5,00102E1,1006.708496,806.171265,691.325684,1020.039307,1025.386475,989.774292,784.503601,1261.884399,1046.455566,1109.039917,1027.218506,742.924438,853,162,10,10.1

In [50]:
## Filtering for years between 2010-2020

climate_df_filtered = climate_df[(climate_df['Year']>=2010) & (climate_df['Year']<=2020)]
nvdi_df_filtered = nvdi_df[(nvdi_df['YEAR']>=2010) & (nvdi_df['YEAR']<=2020)]
ecv_smos_df_filtered = ecv_smos_df[(ecv_smos_df['YEAR']>=2010) & (ecv_smos_df['YEAR']<=2020)]

In [51]:
## Renaming the required columns

climate_df_filtered. rename(columns = {'TWN_ID':'TWP_ID', 'Year':'YEAR'}, inplace = True)

C:\Users\Navdeep Singh Saini\miniconda3\lib\site-packages\pandas\core\frame.py:5039: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

In [52]:
climate_df_filtered.head(5)

,TWP_ID,YEAR,SumPcpn18_20,SumPcpn19_21,SumPcpn20_22,SumPcpn21_23,SumPcpn22_24,SumPcpn23_25,SumPcpn24_26,SumPcpn25_27,...,AvgPrcnAWHC29_31,AvgPrcnAWHC30_32,AvgPrcnAWHC31_33,AvgPrcnAWHC32_34,AvgPrcnAWHC33_35,AvgPrcnAWHC34_36,AvgPrcnAWHC35_37,AvgPrcnAWHC36_38,AvgPrcnAWHC37_39,AvgPrcnAWHC38_40
25,00101E1,2010,53.6,111.1,109.7,117.9,46.4,69.3,60.0,44.6,...,0.182381,0.182857,0.184762,0.206667,0.361905,0.546667,0.767619,0.844762,0.873810,0.867143
26,00101E1,2011,51.6,49.2,57.8,31.1,30.3,63.2,65.1,75.6,...,0.078571,0.054286,0.047143,0.038571,0.068571,0.109524,0.141429,0.259524,0.373810,0.487143
27,00101E1,2012,28.7,43.2,43.2,58.7,59.2,82.3,51.8,44.7,...,0.029524,0.025238,0.061429,0.095238,0.121905,0.111905,0.092381,0.071905,0.058095,0.095714
28,00101E1,2013,41.1,75.9,114.6,83.5,47.5,27.7,42.8,37.8,...,0.492857,0.387143,0.237143,0.133333,0.109524,0.182381,0.254286,0.271905,0.252381,0.285714
29,00101E1,2014,44.3,49.6,49.0,60.1,59.4,76.1,113.4,101.1,...,0.400000,0.287143,0.146667,0.089048,0.138571,0.206190,0.233810,0.227619,0.242381,0.290000

In [53]:
nvdi_df_filtered.head(5)

,TWP_ID,YEAR,NDVI18_20,NDVI19_21,NDVI20_22,NDVI21_23,NDVI22_24,NDVI23_25,NDVI24_26,NDVI25_27,...,NDVI28_30,NDVI29_31,NDVI30_32,NDVI31_33,NDVI32_34,NDVI33_35,NDVI34_36,NDVI35_37,NDVI36_38,NDVI_MAX
10,00101E1,2010,0.300281,0.352352,0.426270,0.501075,0.578762,0.628569,0.654544,0.659907,...,0.679418,0.660112,0.641447,0.614532,0.562060,0.515623,0.473639,0.449115,0.420179,0.704843
11,00101E1,2011,0.259221,0.277087,0.302071,0.351310,0.408707,0.485260,0.561378,0.626498,...,0.745421,0.779282,0.764578,0.727995,0.671003,0.616575,0.554921,0.483088,0.393300,0.795756
12,00101E1,2012,0.305500,0.347146,0.405769,0.471755,0.545110,0.620555,0.681289,0.719817,...,0.743998,0.687361,0.621416,0.561836,0.521024,0.465109,0.408289,0.342285,0.294763,0.773338
13,00101E1,2013,0.217645,0.225827,0.249456,0.283105,0.335140,0.413687,0.524696,0.620474,...,0.790481,0.799692,0.792240,0.767406,0.731984,0.672456,0.612224,0.547149,0.475303,0.816231
14,00101E1,2014,0.218710,0.227899,0.252385,0.292871,0.339906,0.430620,0.520763,0.616722,...,0.685497,0.724684,0.761682,0.755862,0.712256,0.654530,0.595977,0.544310,0.480432,0.781585

In [54]:
climate_nvdi_merged = pd.merge(climate_df_filtered, nvdi_df_filtered, on=['TWP_ID', 'YEAR'], how='inner')

In [55]:
climate_nvdi_merged.head(5)

,TWP_ID,YEAR,SumPcpn18_20,SumPcpn19_21,SumPcpn20_22,SumPcpn21_23,SumPcpn22_24,SumPcpn23_25,SumPcpn24_26,SumPcpn25_27,...,NDVI28_30,NDVI29_31,NDVI30_32,NDVI31_33,NDVI32_34,NDVI33_35,NDVI34_36,NDVI35_37,NDVI36_38,NDVI_MAX
0,00101E1,2010,53.6,111.1,109.7,117.9,46.4,69.3,60.0,44.6,...,0.679418,0.660112,0.641447,0.614532,0.562060,0.515623,0.473639,0.449115,0.420179,0.704843
1,00101E1,2011,51.6,49.2,57.8,31.1,30.3,63.2,65.1,75.6,...,0.745421,0.779282,0.764578,0.727995,0.671003,0.616575,0.554921,0.483088,0.393300,0.795756
2,00101E1,2012,28.7,43.2,43.2,58.7,59.2,82.3,51.8,44.7,...,0.743998,0.687361,0.621416,0.561836,0.521024,0.465109,0.408289,0.342285,0.294763,0.773338
3,00101E1,2013,41.1,75.9,114.6,83.5,47.5,27.7,42.8,37.8,...,0.790481,0.799692,0.792240,0.767406,0.731984,0.672456,0.612224,0.547149,0.475303,0.816231
4,00101E1,2014,44.3,49.6,49.0,60.1,59.4,76.1,113.4,101.1,...,0.685497,0.724684,0.761682,0.755862,0.712256,0.654530,0.595977,0.544310,0.480432,0.781585

In [56]:
crop_yield_canola_col=["TWP_ID","ECODISTRICT_ID","ECOREGION_ID","ECOZONE_ID","ECOPROVINCE_ID"]+[col for col in crop_yield_canola_df if col.startswith("YieldKgAcre")]
crop_yield_canola=crop_yield_canola_df[crop_yield_canola_col]
crop_yield_canola_melt=pd.melt(crop_yield_canola,id_vars=['TWP_ID','ECODISTRICT_ID','ECOREGION_ID','ECOZONE_ID','ECOPROVINCE_ID'],var_name='YEAR',value_name='YieldKgAcre')
crop_yield_canola_melt["YEAR"]=crop_yield_canola_melt["YEAR"].str.slice(start=11)

In [57]:
crop_yield_canola_melt.head(10)

,TWP_ID,ECODISTRICT_ID,ECOREGION_ID,ECOZONE_ID,ECOPROVINCE_ID,YEAR,YieldKgAcre
0,00101E1,852,162,10,10.1,2010,867.766846
1,00101W1,852,162,10,10.1,2010,673.685028
2,00101W2,796,157,10,10.3,2010,824.303864
3,00101W3,832,159,10,10.3,2010,432.694122
4,00102E1,853,162,10,10.1,2010,1006.708496
5,00102W1,852,162,10,10.1,2010,869.040283
6,00102W2,796,157,10,10.3,2010,823.876709
7,00102W3,832,159,10,10.3,2010,430.036743
8,00103E1,853,162,10,10.1,2010,820.111633
9,00103W1,852,162,10,10.1,2010,1161.746033

In [58]:
crop_yield_canola_melt['YEAR'] = crop_yield_canola_melt['YEAR'].astype(int)

In [59]:
climate_nvdi_crop_yield_canola = pd.merge(climate_nvdi_merged, crop_yield_canola_melt, on=['TWP_ID', 'YEAR'], how='inner')
climate_nvdi_crop_yield_canola.head(5)

,TWP_ID,YEAR,SumPcpn18_20,SumPcpn19_21,SumPcpn20_22,SumPcpn21_23,SumPcpn22_24,SumPcpn23_25,SumPcpn24_26,SumPcpn25_27,...,NDVI33_35,NDVI34_36,NDVI35_37,NDVI36_38,NDVI_MAX,ECODISTRICT_ID,ECOREGION_ID,ECOZONE_ID,ECOPROVINCE_ID,YieldKgAcre
0,00101E1,2010,53.6,111.1,109.7,117.9,46.4,69.3,60.0,44.6,...,0.515623,0.473639,0.449115,0.420179,0.704843,852,162,10,10.1,867.766846
1,00101E1,2011,51.6,49.2,57.8,31.1,30.3,63.2,65.1,75.6,...,0.616575,0.554921,0.483088,0.393300,0.795756,852,162,10,10.1,746.765442
2,00101E1,2012,28.7,43.2,43.2,58.7,59.2,82.3,51.8,44.7,...,0.465109,0.408289,0.342285,0.294763,0.773338,852,162,10,10.1,787.231293
3,00101E1,2013,41.1,75.9,114.6,83.5,47.5,27.7,42.8,37.8,...,0.672456,0.612224,0.547149,0.475303,0.816231,852,162,10,10.1,1131.823547
4,00101E1,2014,44.3,49.6,49.0,60.1,59.4,76.1,113.4,101.1,...,0.654530,0.595977,0.544310,0.480432,0.781585,852,162,10,10.1,881.470978

In [60]:
num = climate_nvdi_crop_yield_canola._get_numeric_data()
num[num < 0] = 0

In [61]:
climate_nvdi_crop_yield_canola.isnull().sum()

TWP_ID              0
YEAR                0
SumPcpn18_20        0
SumPcpn19_21        0
SumPcpn20_22        0
                 ...
ECODISTRICT_ID      0
ECOREGION_ID        0
ECOZONE_ID          0
ECOPROVINCE_ID      0
YieldKgAcre       110
Length: 153, dtype: int64

In [62]:
climate_nvdi_crop_yield_canola["YieldKgAcre"].fillna("NA", inplace = True)

In [63]:
climate_nvdi_crop_yield_canola.isnull().values.any()

False

In [64]:
ecv_smos_df_filtered = ecv_smos_df_filtered[(ecv_smos_df_filtered['VALID_COUNT']/ecv_smos_df_filtered['TOTAL_COUNT'])>=0.5]

In [65]:
ecv_smos_df_filtered

,TWP_ID,VALID_COUNT,MIN,MAX,RANGE,MEAN,TOTAL_COUNT,YEAR,DOY,WEEK
0,00101E1,98,32.693829,32.693829,0.000000,32.693825,98,2011,129,19
1,00101W1,95,30.032328,32.693829,2.661501,30.844786,95,2011,129,19
2,00101W2,90,31.222174,31.222174,0.000000,31.222170,90,2011,129,19
3,00102E1,87,32.693829,39.018414,6.324585,35.456284,87,2011,129,19
4,00102W1,95,30.032328,30.032328,0.000000,30.032320,95,2011,129,19
...,...,...,...,...,...,...,...,...,...,...
1546027,11014W5,59,10.384171,18.794367,8.410195,14.375449,59,2019,231,33
1546028,11015W5,44,18.794367,21.711824,2.917458,18.993284,44,2019,231,33
1546029,11016W5,4,21.711824,21.711824,0.000000,21.711824,4,2019,231,33
1546030,11017W5,38,21.308325,21.711824,0.403500,21.435749,38,2019,231,33
1546031,11018W5,43,19.674173,21.308325,1.634151,21.042301,43,2019,231,33

In [66]:
print("Minimum Year is:", min(ecv_smos_df_filtered['WEEK']))
print("Maximum Year is:", max(ecv_smos_df_filtered['WEEK']))

Minimum Year is: 18
Maximum Year is: 40

In [67]:
ecv_smos_df_filtered['moving'] = ecv_smos_df_filtered.sort_values('WEEK').groupby(['TWP_ID','YEAR']).rolling(3)['MEAN'].mean().droplevel(level=[0,1])

In [68]:
ecv_smos_df_filtered['WEEK'] = ecv_smos_df_filtered['WEEK'].apply(str)
ecv_smos_df_filtered['rolling_week'] = ecv_smos_df_filtered['WEEK']-2
ecv_smos_df_filtered['rolling_week'] = ecv_smos_df_filtered['rolling_week'].apply(str)
ecv_smos_df_filtered['Values'] = "SoilMoisture"+ecv_smos_df_filtered['rolling_week']+"_"+ ecv_smos_df_filtered['WEEK']

In [75]:
ecv_smos_df_filtered.head(100)

,TWP_ID,VALID_COUNT,MIN,MAX,RANGE,MEAN,TOTAL_COUNT,YEAR,DOY,WEEK,moving,rolling_week,Values
0,00101E1,98,32.693829,32.693829,0.000000,32.693825,98,2011,129,19,NaN,17,SoilMoisture17_19
1,00101W1,95,30.032328,32.693829,2.661501,30.844786,95,2011,129,19,NaN,17,SoilMoisture17_19
2,00101W2,90,31.222174,31.222174,0.000000,31.222170,90,2011,129,19,NaN,17,SoilMoisture17_19
3,00102E1,87,32.693829,39.018414,6.324585,35.456284,87,2011,129,19,NaN,17,SoilMoisture17_19
4,00102W1,95,30.032328,30.032328,0.000000,30.032320,95,2011,129,19,NaN,17,SoilMoisture17_19
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,00205W2,45,32.079185,32.079185,0.000000,32.079189,45,2011,129,19,NaN,17,SoilMoisture17_19
96,00206E1,5,31.127321,35.758587,4.631266,34.832336,5,2011,129,19,NaN,17,SoilMoisture17_19
97,00206W1,72,27.036829,28.551823,1.514994,27.289330,72,2011,129,19,NaN,17,SoilMoisture17_19
98,00206W2,69,32.079185,33.225891,1.146706,32.694080,69,2011,129,19,NaN,17,SoilMoisture17_19
99,00207E1,14,35.758587,35.758587,0.000000,35.758583,14,2011,129,19,NaN,17,SoilMoisture17_19

In [76]:
# Creating pivot table, to convert long data to wide.
output = pd.pivot_table(data=ecv_smos_df_filtered, index=['TWP_ID', 'YEAR'], values=['moving'], columns=['Values'])

In [77]:
output.columns = output.columns.droplevel(0)    #remove moving
output.columns.name = None                      #remove Values
output = output.reset_index()

In [78]:
output.head()

,TWP_ID,YEAR,SoilMoisture18_20,SoilMoisture19_21,SoilMoisture20_22,SoilMoisture21_23,SoilMoisture22_24,SoilMoisture23_25,SoilMoisture24_26,SoilMoisture25_27,...,SoilMoisture29_31,SoilMoisture30_32,SoilMoisture31_33,SoilMoisture32_34,SoilMoisture33_35,SoilMoisture34_36,SoilMoisture35_37,SoilMoisture36_38,SoilMoisture37_39,SoilMoisture38_40
0,00101E1,2010,NaN,NaN,NaN,NaN,NaN,29.469124,26.039029,21.285326,...,16.960125,18.766207,17.186998,15.461519,19.738222,22.958089,27.206203,26.480087,28.678156,26.308484
1,00101E1,2011,30.041478,30.776526,30.347748,29.370969,24.104584,24.598241,29.466194,31.705049,...,11.656416,13.067006,12.259018,10.962354,11.067690,12.393230,12.878415,16.048892,16.339756,16.916437
2,00101E1,2012,13.364138,13.024097,16.698533,18.498670,20.024051,19.688582,16.879898,13.248060,...,12.259482,11.656875,14.193643,14.463289,13.531056,10.850650,8.974640,7.387093,6.731918,6.235354
3,00101E1,2013,31.146724,30.798302,32.301329,32.746259,25.065036,18.048107,18.219820,14.677471,...,20.228838,20.471527,17.000901,16.707677,18.353434,20.625101,22.306758,17.412074,15.750943,15.660199
4,00101E1,2014,27.567995,25.415198,23.517646,22.238960,18.463416,21.842931,26.899768,35.047699,...,16.070272,14.138311,10.398432,12.179173,15.950552,21.388720,20.752620,21.834875,21.248439,23.679921

In [79]:
final_df = pd.merge(climate_nvdi_crop_yield_canola, output, on=['TWP_ID', 'YEAR'], how='inner')

In [85]:
pd.set_option('display.max_columns', None)
final_df.head()

,TWP_ID,YEAR,SumPcpn18_20,SumPcpn19_21,SumPcpn20_22,SumPcpn21_23,SumPcpn22_24,SumPcpn23_25,SumPcpn24_26,SumPcpn25_27,SumPcpn26_28,SumPcpn27_29,SumPcpn28_30,SumPcpn29_31,SumPcpn30_32,SumPcpn31_33,SumPcpn32_34,SumPcpn33_35,SumPcpn34_36,SumPcpn35_37,SumPcpn36_38,SumPcpn37_39,SumPcpn38_40,SumEGDD_C18_20,SumEGDD_C19_21,SumEGDD_C20_22,SumEGDD_C21_23,SumEGDD_C22_24,SumEGDD_C23_25,SumEGDD_C24_26,SumEGDD_C25_27,SumEGDD_C26_28,SumEGDD_C27_29,SumEGDD_C28_30,SumEGDD_C29_31,SumEGDD_C30_32,SumEGDD_C31_33,SumEGDD_C32_34,SumEGDD_C33_35,SumEGDD_C34_36,SumEGDD_C35_37,SumEGDD_C36_38,SumEGDD_C37_39,SumEGDD_C38_40,SumHeatD18_20,SumHeatD19_21,SumHeatD20_22,SumHeatD21_23,SumHeatD22_24,SumHeatD23_25,SumHeatD24_26,SumHeatD25_27,SumHeatD26_28,SumHeatD27_29,SumHeatD28_30,SumHeatD29_31,SumHeatD30_32,SumHeatD31_33,SumHeatD32_34,SumHeatD33_35,SumHeatD34_36,SumHeatD35_37,SumHeatD36_38,SumHeatD37_39,SumHeatD38_40,SumFrostD18_20,SumFrostD19_21,SumFrostD20_22,SumFrostD21_23,SumFrostD22_24,SumFrostD23_25,SumFrostD24_26,SumFrostD25_27,SumFrostD26_28,SumFrostD27_29,SumFrostD28_30,SumFrostD29_31,SumFrostD30_32,SumFrostD31_33,SumFrostD32_34,SumFrostD33_35,SumFrostD34_36,SumFrostD35_37,SumFrostD36_38,SumFrostD37_39,SumFrostD38_40,AvgSI18_20,AvgSI19_21,AvgSI20_22,AvgSI21_23,AvgSI22_24,AvgSI23_25,AvgSI24_26,AvgSI25_27,AvgSI26_28,AvgSI27_29,AvgSI28_30,AvgSI29_31,AvgSI30_32,AvgSI31_33,AvgSI32_34,AvgSI33_35,AvgSI34_36,AvgSI35_37,AvgSI36_38,AvgSI37_39,AvgSI38_40,AvgPrcnAWHC18_20,AvgPrcnAWHC19_21,AvgPrcnAWHC20_22,AvgPrcnAWHC21_23,AvgPrcnAWHC22_24,AvgPrcnAWHC23_25,AvgPrcnAWHC24_26,AvgPrcnAWHC25_27,AvgPrcnAWHC26_28,AvgPrcnAWHC27_29,AvgPrcnAWHC28_30,AvgPrcnAWHC29_31,AvgPrcnAWHC30_32,AvgPrcnAWHC31_33,AvgPrcnAWHC32_34,AvgPrcnAWHC33_35,AvgPrcnAWHC34_36,AvgPrcnAWHC35_37,AvgPrcnAWHC36_38,AvgPrcnAWHC37_39,AvgPrcnAWHC38_40,NDVI18_20,NDVI19_21,NDVI20_22,NDVI21_23,NDVI22_24,NDVI23_25,NDVI24_26,NDVI25_27,NDVI26_28,NDVI27_29,NDVI28_30,NDVI29_31,NDVI30_32,NDVI31_33,NDVI32_34,NDVI33_35,NDVI34_36,NDVI35_37,NDVI36_38,NDVI_MAX,ECODISTRICT_ID,ECOREGION_ID,ECOZONE_ID,ECOPROVINCE_ID,YieldKgAcre,SoilMoisture18_20,SoilMoisture19_21,SoilMoisture20_22,SoilMoisture21_23,SoilMoisture22_24,SoilMoisture23_25,SoilMoisture24_26,SoilMoisture25_27,SoilMoisture26_28,SoilMoisture27_29,SoilMoisture28_30,SoilMoisture29_31,SoilMoisture30_32,SoilMoisture31_33,SoilMoisture32_34,SoilMoisture33_35,SoilMoisture34_36,SoilMoisture35_37,SoilMoisture36_38,SoilMoisture37_39,SoilMoisture38_40
0,00101E1,2010,53.6,111.1,109.7,117.9,46.4,69.3,60.0,44.6,29.9,52.4,65.6,50.7,45.1,32.0,35.7,72.9,94.5,92.6,76.0,51.3,48.4,148.40,219.60,240.35,213.80,228.3,260.95,302.80,317.70,315.45,307.55,316.55,326.25,340.70,317.25,306.20,257.35,222.95,158.50,127.75,123.55,160.35,0,0,0,0,0,0,3,4,4,1,2,3,6,5,5,2,1,0,0,0,0,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,2,3,3,2,0.515238,0.481429,0.412857,0.276667,0.170000,0.105714,0.086667,0.097143,0.176190,0.324762,0.354286,0.413333,0.496190,0.622381,0.682381,0.628571,0.609524,0.565238,0.561905,0.563333,0.580476,0.862857,0.872381,0.851429,0.836190,0.741905,0.695714,0.605714,0.482381,0.309048,0.215238,0.203333,0.182381,0.182857,0.184762,0.206667,0.361905,0.546667,0.767619,0.844762,0.873810,0.867143,0.300281,0.352352,0.426270,0.501075,0.578762,0.628569,0.654544,0.659907,0.676674,0.681467,0.679418,0.660112,0.641447,0.614532,0.562060,0.515623,0.473639,0.449115,0.420179,0.704843,852,162,10,10.1,867.766846,NaN,NaN,NaN,NaN,NaN,29.469124,26.039029,21.285326,15.008955,13.551171,16.047309,16.960125,18.766207,17.186998,15.461519,19.738222,22.958089,27.206203,26.480087,28.678156,26.308484
1,00101E1,2011,51.6,49.2,57.8,31.1,30.3,63.2,65.1,75.6,28.3,25.2,7.9,17.2,20.2,18.5,8.2,22.6,22.6,23.8,56.7,57.6,59.1,142.35,136.75,173.60,169.15,232.2,248.35,287.60,306.45,331.60,339.05,332.45,332.95,321.00,308.25,308.65,300.40,307.95,242.70,197.70,155.35,193.10,0,0,0,0,0,0,1,2,5,7,6,3,0,0,3,3,6,3,3,0,1,4,4,3,2,0,0,0,0,0,0,0,0,0,0,0,0,0,3,4,5,2,0.600952,0.551429,0.511905,0.468571,0.402857,0.290952,0.170476,0.093333,0.093333,0.225714,0.467143,0.684762,0.716667,0.764762,0.829048,0.890476,0.814286,0.751429,0.693333,0.662857,0.626190,0.821905,0.844762,0.862381,0.858095,0.800476,0.765714,0.717143,0.667143,0.510476,0.330476,0.166190,0.078571,0.054286,0.047143,0.038571,0.068571,0.109524,0.141429,0.259524,0.373810,0.487143,0.259221,0.277087,0.302071,0.351310,0.408707,0.485260,0.561378,0.626498,0.659092,0.700844,0.745421,0.779282,0.764578,0.727995,0.671003,0.616575,0.554921,0.483088,0.393300,0.795756,852,162,10,10.1,746.765442,30.041478,30.776526,30.347748,29.370969,24.104584,24.598241,29.466194,31.705049,25.024095,17.118592,12.088430,11.656416,13.067006,12.259018,10.962354,11.067690,12.393230,12.878415,16.048892,16.339756,16.916437
2,00101E1,2012,28.7,43.2,43.2,58.7,59.2,82.3,51.8,44.7,31.3,34.2,19.9,8.6,16.5,23.6,28.2,17.5,11.3,1.8,2.9,2.0,25.6,177.85,175.65,169.95,209.05,239.9,263.10,272.95,313.45,360.70,365.30,357.85,340.25,319.70,281.05,284.30,295.90,289.55,239.85,152.25,135.10,95.45,1,1,1,1,1,1,2,4,9,8,9,5,4,1,4,7,7,3,0,0,0,2,3,3,2,1,0,0,0,0,0,0,0,0,0,0,0,1,3,8,9,11,0.649524,0.598095,0.526190,0.478095,0.356667,0.241905,0.149524,0.174762,0.262381,0.388095,0.640000,0.808571,0.905714,0.842381,0.800952,0.764762,0.781429,0.813333,0.856667,0.883333,0.846667,0.439048,0.437619,0.459524,0.470952,0.498571,0.527619,0.509524,0.405238,0.239048,0.123333,0.050952,0.029524,0.025238,0.061429,0.095238,0.121905,0.111905,0.092381,0.071905,0.058095,0.095714,0.305500,0.347146,0.405769,0.471755,0.545110,0.620555,0.681289,0.719817,0.741421,0.760645,0.743998,0.687361,0.621416,0.561836,0.521024,0.465109,0.408289,0.342285,0.294763,0.773338,852,162,10,10.1,787.231293,13.364138,13.024097,16.698533,18.498670,20.024051,19.688582,16.879898,13.248060,10.257014,13.364488,12.164644,12.259482,11.656875,14.193643,14.463289,13.531056,10.850650,8.974640,7.387093,6.731918,6.235354
3,00101E1,2013,41.1,75.9,114.6,83.5,47.5,27.7,42.8,37.8,60.1,84.1,96.8,68.4,32.1,19.0,17.2,42.4,42.5,35.5,4.8,23.0,24.1,97.30,146.95,184.90,188.60,225.7,265.95,312.30,347.00,352.65,326.60,277.10,245.25,227.60,246.85,286.25,331.90,329.50,290.45,223.70,199.70,156.25,1,1,1,0,0,1,3,6,5,3,0,0,0,0,4,7,9,5,2,0,0,11,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,3,0.613810,0.614762,0.597619,0.546190,0.541905,0.570000,0.432381,0.323810,0.148571,0.126667,0.060000,0.036667,0.078095,0.253333,0.516190,0.696190,0.723810,0.662381,0.675714,0.720952,0.688571,0.790476,0.808571,0.850952,0.872857,0.816667,0.735238,0.704762,0.620000,0.587143,0.529524,0.549524,0.492857,0.387143,0.237143,0.133333,0.109524,0.182381,0.254286,0.271905,0.252381,0.285714,0.217645,0.225827,0.249456,0.283105,0.335140,0.413687,0.524696,0.620474,0.700725,0.746835,0.790481,0.799692,0.792240,0.767406,0.731984,0.672456,0.612224,0.547149,0.475303,0.816231,852,162,10,10.1,1131.823547,31.146724,30.798302,32.301329,32.746259,25.065036,18.048107,18.219820,14.677471,16.049866,15.161645,20.299085,20.228838,20.471527,17.000901,16.707677,18.353434,20.625101,22.306758,17.412074,15.750943,15.660199
4,00101E1,2014,44.3,49.6,49.0,60.1,59.4,76.1,113.4,101.1,81.1,25.2,35.3,29.8,29.8,2.3,34.9,54.4,54.8,27.7,26.7,29.9,27.7,51.50,112.70,191.90,251.65,259.9,240.80,260.05,278.25,286.35,287.80,288.20,289.80,306.55,315.30,324.55,283.15,253.45,178.90,162.70,178.70,173.20,0,1,2,2,1,0,0,1,1,2,1,1,1,3,3,2,0,0,0,0,0,12,8,5,1,0,0,0,0,0,0,0,0,0,0,0,0,0,3,5,5,4,0.561905,0.569048,0.567143,0.567143,0.570000,0.531429,0.489048,0.388095,0.280000,0.234286,0.200476,0.214286,0.342381,0.554762,0.764286,0.610952,0.401429,0.367143,0.523333,0.663333,0.633810,0.611905,0.647619,0.704762,0.760476,0.775238,0.819048,0.865714,0.901429,0.825238,0.666190,0.535714,0.400000,0.287143,0.146667,0.089048,0.138571,0.206190,0.233810,0.227619,0.242381,0.290000,0.218710,0.227899,0.252385,0.292871,0.339906,0.430620,0.520763,0.616722,0.646788,0.664744,0.685497,0.724684,0.761682,0.755862,0.712256,0.654530,0.595977,0.544310,0.480432,0.781585,852,162,10,10.1,881.470978,27.567995,25.415198,23.517646,22.238960,18.463416,21.842931,26.899768,35.047699,31.360631,24.632144,18.857822,16.070272,14.138311,10.398432,12.179173,15.950552,21.388720,20.752620,21.834875,21.248439,23.679921