In [26]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import pandas as pd

In [27]:
df = pd.read_csv('final_data.csv')

In [28]:
df.head(10)

,TWP_ID,ECODISTRICT_ID,YEAR,YieldKgAcre,SumPcpn18_20,SumPcpn19_21,SumPcpn20_22,SumPcpn21_23,SumPcpn22_24,SumPcpn23_25,...,SoilMoisture29_31,SoilMoisture30_32,SoilMoisture31_33,SoilMoisture32_34,SoilMoisture33_35,SoilMoisture34_36,SoilMoisture35_37,SoilMoisture36_38,SoilMoisture37_39,SoilMoisture38_40
0,1.01E+03,852,2010,867.766846,53.6,111.1,109.7,117.9,46.4,69.3,...,16.960125,18.766207,17.186998,15.461519,19.738222,22.958089,27.206203,26.480087,28.678156,26.308484
1,00101W1,852,2010,673.685028,57.2,114.7,110.5,114.0,46.2,68.1,...,16.328520,17.926029,16.787544,14.779726,20.245149,23.608204,28.560990,27.324254,29.079177,26.927224
2,00101W2,796,2010,824.303864,39.0,96.4,109.8,101.2,111.4,153.0,...,13.117879,12.869142,12.831834,14.126196,16.385776,18.650751,20.287069,20.514132,19.564788,16.681692
3,1.02E+03,853,2010,1006.708496,37.5,158.2,157.8,161.4,46.9,79.5,...,17.060778,18.699156,17.345822,15.998957,20.091525,22.761273,26.337430,25.559602,27.611729,25.575794
4,00102W1,852,2010,869.040283,57.2,114.7,110.5,114.0,46.2,68.1,...,16.050993,17.556860,16.612026,14.480150,20.467884,23.893858,29.156274,27.695178,29.255386,27.199097
5,00102W2,796,2010,823.876709,29.8,59.0,85.2,84.2,99.6,98.1,...,12.764556,12.677635,12.789246,14.079408,16.463949,18.748863,20.442023,20.561543,19.685445,16.877247
6,1.03E+03,853,2010,820.111633,37.5,158.2,157.8,161.4,46.9,79.5,...,17.190572,18.612701,17.550619,16.691967,20.547095,22.507483,25.217171,24.372655,26.236585,24.630997
7,00103W1,852,2010,1161.746033,86.9,116.2,100.6,107.5,45.3,64.0,...,14.704203,14.777767,13.545633,11.725336,17.627468,23.557086,28.983659,26.644216,25.239740,21.723549
8,00103W2,796,2010,742.240295,29.8,59.0,85.2,84.2,99.6,98.1,...,10.871751,11.651702,12.561097,13.828763,16.882740,19.274461,21.272135,20.815523,20.331824,17.924860
9,1.04E+03,726,2010,726.107849,37.5,158.2,157.8,161.4,46.9,79.5,...,17.499952,18.814546,17.683490,16.658587,20.300749,22.029694,24.528982,23.675503,25.669904,24.306126

In [29]:
df.drop(['TWP_ID','ECODISTRICT_ID','YEAR'], axis=1, inplace= True)

In [30]:
df.head()

,YieldKgAcre,SumPcpn18_20,SumPcpn19_21,SumPcpn20_22,SumPcpn21_23,SumPcpn22_24,SumPcpn23_25,SumPcpn24_26,SumPcpn25_27,SumPcpn26_28,...,SoilMoisture29_31,SoilMoisture30_32,SoilMoisture31_33,SoilMoisture32_34,SoilMoisture33_35,SoilMoisture34_36,SoilMoisture35_37,SoilMoisture36_38,SoilMoisture37_39,SoilMoisture38_40
0,867.766846,53.6,111.1,109.7,117.9,46.4,69.3,60.0,44.6,29.9,...,16.960125,18.766207,17.186998,15.461519,19.738222,22.958089,27.206203,26.480087,28.678156,26.308484
1,673.685028,57.2,114.7,110.5,114.0,46.2,68.1,55.9,34.9,29.6,...,16.328520,17.926029,16.787544,14.779726,20.245149,23.608204,28.560990,27.324254,29.079177,26.927224
2,824.303864,39.0,96.4,109.8,101.2,111.4,153.0,163.6,98.8,42.4,...,13.117879,12.869142,12.831834,14.126196,16.385776,18.650751,20.287069,20.514132,19.564788,16.681692
3,1006.708496,37.5,158.2,157.8,161.4,46.9,79.5,67.5,40.4,6.6,...,17.060778,18.699156,17.345822,15.998957,20.091525,22.761273,26.337430,25.559602,27.611729,25.575794
4,869.040283,57.2,114.7,110.5,114.0,46.2,68.1,55.9,34.9,29.6,...,16.050993,17.556860,16.612026,14.480150,20.467884,23.893858,29.156274,27.695178,29.255386,27.199097

In [31]:
Y = df['YieldKgAcre']

In [32]:
df.drop('YieldKgAcre', axis=1, inplace= True)

In [33]:
df.head()

,SumPcpn18_20,SumPcpn19_21,SumPcpn20_22,SumPcpn21_23,SumPcpn22_24,SumPcpn23_25,SumPcpn24_26,SumPcpn25_27,SumPcpn26_28,SumPcpn27_29,...,SoilMoisture29_31,SoilMoisture30_32,SoilMoisture31_33,SoilMoisture32_34,SoilMoisture33_35,SoilMoisture34_36,SoilMoisture35_37,SoilMoisture36_38,SoilMoisture37_39,SoilMoisture38_40
0,53.6,111.1,109.7,117.9,46.4,69.3,60.0,44.6,29.9,52.4,...,16.960125,18.766207,17.186998,15.461519,19.738222,22.958089,27.206203,26.480087,28.678156,26.308484
1,57.2,114.7,110.5,114.0,46.2,68.1,55.9,34.9,29.6,59.5,...,16.328520,17.926029,16.787544,14.779726,20.245149,23.608204,28.560990,27.324254,29.079177,26.927224
2,39.0,96.4,109.8,101.2,111.4,153.0,163.6,98.8,42.4,24.4,...,13.117879,12.869142,12.831834,14.126196,16.385776,18.650751,20.287069,20.514132,19.564788,16.681692
3,37.5,158.2,157.8,161.4,46.9,79.5,67.5,40.4,6.6,49.6,...,17.060778,18.699156,17.345822,15.998957,20.091525,22.761273,26.337430,25.559602,27.611729,25.575794
4,57.2,114.7,110.5,114.0,46.2,68.1,55.9,34.9,29.6,59.5,...,16.050993,17.556860,16.612026,14.480150,20.467884,23.893858,29.156274,27.695178,29.255386,27.199097

In [34]:
X = df

In [35]:
# test_size: what proportion of original data is used for test set
train_img, test_img, train_lbl, test_lbl = train_test_split(X, Y, test_size=0.2, random_state=1)

In [36]:
scaler = StandardScaler()
# Fit on training set only.
scaler.fit(train_img)
# Apply transform to both the training set and the test set.
train_img = scaler.transform(train_img)
test_img = scaler.transform(test_img)

In [37]:
# Make an instance of the Model
pca = PCA(.95)

In [38]:
train_image = pca.fit_transform(train_img)

In [39]:
pca.n_components_

40

In [40]:
test_img = pca.transform(test_img)

In [41]:
train_image.shape

(33605, 40)

In [21]:
principalDf = pd.DataFrame(
train_image, 
    columns = [
    'pc 1', 
    'pc 2',
    'pc 3', 
    'pc 4',
    'pc 5', 
    'pc 6',
    'pc 7', 
    'pc 8',
    'pc 9', 
    'pc 10',
    'pc 11', 
    'pc 12',
    'pc 13', 
    'pc 14',
    'pc 15', 
    'pc 16',
    'pc 17', 
    'pc 18',
    'pc 19', 
    'pc 20',
    'pc 21', 
    'pc 22',
    'pc 23', 
    'pc 24',
    'pc 25', 
    'pc 26',
    'pc 27', 
    'pc 28',
    'pc 29', 
    'pc 30',
    'pc 31', 
    'pc 32',
    'pc 33', 
    'pc 34',
    'pc 35', 
    'pc 36',
    'pc 37', 
    'pc 38',
    'pc 39',
    'pc 40'
    ]
)

In [42]:
principalDf.head()

,pc 1,pc 2,pc 3,pc 4,pc 5,pc 6,pc 7,pc 8,pc 9,pc 10,...,pc 31,pc 32,pc 33,pc 34,pc 35,pc 36,pc 37,pc 38,pc 39,pc 40
0,0.981490,-4.104351,-3.075636,1.672974,2.288725,-4.588676,-0.909914,3.306961,3.627524,-1.279427,...,-1.218258,-0.286630,0.599988,-1.454460,2.156702,-0.409706,1.066999,-0.681590,-0.238492,0.129916
1,-7.791216,2.613004,0.830375,-1.025651,3.416493,3.389481,1.251507,-0.126173,-2.352365,2.371180,...,-0.860122,-1.037386,1.067690,0.980582,-0.460453,-0.786492,1.468126,0.285908,0.406989,1.072721
2,-0.376696,7.322101,-1.072659,-2.608636,-0.538741,-1.348603,-0.192584,-0.643278,-1.783858,-1.137858,...,-0.318585,0.613806,-0.606472,-0.153541,0.899754,-0.261018,0.517878,-1.460502,-0.189687,-0.551427
3,5.457436,-5.720625,5.474761,5.098252,-0.736394,-1.571867,-2.363899,-0.656865,-2.260579,-3.702239,...,1.410063,0.126420,-0.655503,-0.622267,0.510734,0.631345,-0.518350,-0.114530,0.048497,-0.594910
4,2.259284,-2.850893,5.778290,-4.968689,-6.442701,-0.346797,0.748776,0.143758,3.315815,0.834805,...,-0.345381,-1.003507,1.752235,0.880358,0.088558,-0.506863,-0.302203,0.106614,0.134279,0.184435

In [43]:
finalDf = pd.concat([principalDf, Y], axis = 1)

In [44]:
finalDf.head()

,pc 1,pc 2,pc 3,pc 4,pc 5,pc 6,pc 7,pc 8,pc 9,pc 10,...,pc 32,pc 33,pc 34,pc 35,pc 36,pc 37,pc 38,pc 39,pc 40,YieldKgAcre
0,0.981490,-4.104351,-3.075636,1.672974,2.288725,-4.588676,-0.909914,3.306961,3.627524,-1.279427,...,-0.286630,0.599988,-1.454460,2.156702,-0.409706,1.066999,-0.681590,-0.238492,0.129916,867.766846
1,-7.791216,2.613004,0.830375,-1.025651,3.416493,3.389481,1.251507,-0.126173,-2.352365,2.371180,...,-1.037386,1.067690,0.980582,-0.460453,-0.786492,1.468126,0.285908,0.406989,1.072721,673.685028
2,-0.376696,7.322101,-1.072659,-2.608636,-0.538741,-1.348603,-0.192584,-0.643278,-1.783858,-1.137858,...,0.613806,-0.606472,-0.153541,0.899754,-0.261018,0.517878,-1.460502,-0.189687,-0.551427,824.303864
3,5.457436,-5.720625,5.474761,5.098252,-0.736394,-1.571867,-2.363899,-0.656865,-2.260579,-3.702239,...,0.126420,-0.655503,-0.622267,0.510734,0.631345,-0.518350,-0.114530,0.048497,-0.594910,1006.708496
4,2.259284,-2.850893,5.778290,-4.968689,-6.442701,-0.346797,0.748776,0.143758,3.315815,0.834805,...,-1.003507,1.752235,0.880358,0.088558,-0.506863,-0.302203,0.106614,0.134279,0.184435,869.040283